CC=gcc
cubo.o: cubo.c               
	$(CC) -c cubo.c

cuarta.o: cuarta.c               
	$(CC) -c cuarta.c

quintilla.o: quintilla.c               
	$(CC) -c quintilla.c

clean:                           
	rm  *.o